// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TSystems.ASPNETCoreMVC.Torneio.Context;

namespace TSystems.ASPNETCoreMVC.Torneio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220329121745_Vencedor")]
    partial class Vencedor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TSystems.ASPNETCoreMVC.Torneio.Models.ChampionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<int>("Habilidades")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDeLutas")
                        .HasColumnType("int");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Champion");
                });

            modelBuilder.Entity("TSystems.ASPNETCoreMVC.Torneio.Models.VencedorModel", b =>
                {
                    b.Property<int>("VencedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChampionId")
                        .HasColumnType("int");

                    b.HasKey("VencedorId");

                    b.HasIndex("ChampionId");

                    b.ToTable("Vencedor");
                });

            modelBuilder.Entity("TSystems.ASPNETCoreMVC.Torneio.Models.VencedorModel", b =>
                {
                    b.HasOne("TSystems.ASPNETCoreMVC.Torneio.Models.ChampionModel", "Champion")
                        .WithMany()
                        .HasForeignKey("ChampionId");

                    b.Navigation("Champion");
                });
#pragma warning restore 612, 618
        }
    }
}
